"""Guided first-time setup: dependency checks and config generation.

The interactive shell lives in the CLI (`jobtailor init`); everything
decision-shaped here is a pure, testable function.
"""

from __future__ import annotations

import shutil
from dataclasses import dataclass
from pathlib import Path

import yaml

_HEADER = """\
# JobTailor configuration
# Generated by `jobtailor init`. Edit freely; see config.example.yaml for
# the full reference of every option.
"""


@dataclass
class DepCheck:
    name: str
    ok: bool
    hint: str


def check_dependencies() -> list[DepCheck]:
    """Check external tools JobTailor shells out to."""
    checks = [
        DepCheck(
            "tectonic (PDF compiler)",
            shutil.which("tectonic") is not None,
            "install with: brew install tectonic",
        ),
        DepCheck(
            "ego-browser (form auto-fill)",
            shutil.which("ego-browser") is not None,
            "needed for pre_fill / full_auto apply modes",
        ),
        DepCheck(
            "opencode (LLM resume tailoring)",
            shutil.which("opencode") is not None,
            "needed for the tailor stage",
        ),
    ]
    return checks


def validate_resume_dir(path: str) -> tuple[Path | None, str]:
    """Return (resolved_path, "") when the dir holds a resume.tex, else (None, reason)."""
    p = Path(path).expanduser()
    if not p.exists():
        return None, f"directory does not exist: {p}"
    if not p.is_dir():
        return None, f"not a directory: {p}"
    if not (p / "resume.tex").exists():
        return None, f"resume.tex not found in {p}"
    return p, ""


_DEFAULT_SOURCES = {
    "adzuna": True,
    "wellfound": True,
    "glassdoor": False,
    "foundit": False,
    "simplyhired": False,
    "dailyremote": False,
    "linkedin": False,
    "careers": False,
    "mercor": False,
    "outlier": False,
}


def build_config(answers: dict) -> str:
    """Render a config.yaml from wizard answers."""
    gmail = answers.get("gmail") or {"enabled": False}
    cfg = {
        "schedule": {
            "times": answers.get("times") or ["07:00"],
            "jobs_per_run": int(answers.get("jobs_per_run") or 15),
        },
        "discovery": {
            "queries": [
                {"keyword": k, "filters": {"remote": True}}
                for k in (answers.get("keywords") or [])
            ],
            "companies": answers.get("companies") or [],
            "sources": dict(_DEFAULT_SOURCES),
            "max_per_query": 5,
            "max_per_company": 3,
        },
        "resume": {
            "source": answers.get("resume_source") or "~/resume",
            "format": "latex",
            "compiler": "tectonic",
        },
        "llm": {"provider": "opencode", "model": ""},
        "apply": {"mode": answers.get("apply_mode") or "full_auto"},
        "adzuna": {
            "app_id": answers.get("adzuna_id") or "",
            "app_key": answers.get("adzuna_key") or "",
            "country": answers.get("adzuna_country") or "in",
        },
        "gmail": gmail,
    }
    return _HEADER + yaml.safe_dump(cfg, sort_keys=False)
